name: Bug Report
description: Create a report to help us improve
labels: "bug"
body:
- type: markdown
  attributes:
    value: |
      Before logging the bug, please make sure that:

        1. You are using the latest version of `lsp-mode` related packages.
        2. You may also try reproduce the issue using clean environment using the following command:
          ``` bash
          emacs -q -l lsp-start-plain.el
          ```
          where `lsp-start-plain.el` could be downloaded from `https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el`.
          Alternatively, in will be great if you can reproduce the issue using [lsp-docker](https://github.com/emacs-lsp/lsp-docker/) which provides the minimal configurations for `lsp-mode` and ships with most of the language servers.
          3. Check FAQ and Troubleshooting section (https://emacs-lsp.github.io/lsp-mode/page/faq/ and https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/)
          4. Consider providing a minimal project to reproduce the issue with. Note that `lsp-mode` supports 30+ languages and the maintainers of the project are not familiar with all of the languages and a sample project + full steps to reproduce will help a lot.
- type: checkboxes
  id: questions
  attributes:
    label: Please make sure that you check the options below
    options:
      - label: I have tested with the latest melpa version
        required: true
      - label: I have tested with [lsp-start-plain.el](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el#L21-L30)
- type: textarea
  id: bug-description
  attributes:
    label: Bug description
    description: A clear and concise description of what the bug is
  validations:
    required: true
- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to reproduce
    description: Steps to reproduce the behavior(sample project + file which can be used to reproduce the issue with)
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen
  validations:
    required: true
- type: textarea
  id: which-ls
  attributes:
    label: Which Language Server did you use?
    description: Mention which server/language did you use (e. g. lsp-python, lsp-ccls, lsp-java, etc)
  validations:
    required: true
- type: dropdown
  id: which-os
  attributes:
    label: OS
    description: Which os do you use?
    options:
      - Linux
      - MacOS
      - Windows
  validations:
    required: true
- type: textarea
  id: error-callstack
  attributes:
    label: Error callstack
    description: |
      If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of `*lsp-log*` buffer and the content of the server log(use `lsp-workspace-show-log`)

      If `emacs` hangs please do `M-x` `toggle-debug-on-quit` and then do `C-g` when emacs hangs and include the callstack as part of the issue report.

      ``` emacs-lisp
      (setq lsp-print-io t)
      ```
    render: "emacs-lisp"
- type: textarea
  id: anything-else
  attributes:
    label: Anything else?
    description: Let us know if you have any additional context
